version: '3'

networks:
  default:
    name: "BlobOA-Network"

services:
  bloboa-server:
    image: bloboa-server:latest
    container_name: BlobOA-Server
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
    ports:
      - 5200:8080
    build:
      context: ./
      args:
        - C=${CONFIGURATION:?error}
        - E=${DOTNET_ENVIRONMENT:?error}
      dockerfile: ./BlobOA.Server/Dockerfile
      target: final-full

  # bloboa-emailserver:
  #   image: bloboa-emailserver:latest
  #   container_name: BlobOA-EmailServer
  #   environment:
  #     - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
  #   build:
  #     context: ./
  #     args:
  #       - C=${CONFIGURATION}
  #       - E=${DOTNET_ENVIRONMENT}
  #     dockerfile: ./EmailServer/Dockerfile
