version: '3'

networks:
  default:
    name: "BLOBOA-Network"

services:
  appserver:
    image: loopercorp/appserver:latest
    container_name: AppServer
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
    ports:
      - 5300:8080
    build:
      context: ./
      args:
        - C=${CONFIGURATION}
        - E=${DOTNET_ENVIRONMENT}
      dockerfile: ./AppServer/Dockerfile

  emailserver:
    image: loopercorp/emailserver:latest
    container_name: EmailServer
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
    build:
      context: ./
      args:
        - C=${CONFIGURATION}
        - E=${DOTNET_ENVIRONMENT}
      dockerfile: ./EmailServer/Dockerfile

  proxyserver:
    image: loopercorp/proxyserver:latest
    container_name: ProxyServer
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
    ports:
      - 5200:8080
    build:
      context: ./
      args:
        - C=${CONFIGURATION}
        - E=${DOTNET_ENVIRONMENT}
      dockerfile: ./ProxyServer/Dockerfile
